#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFPages.Libraries
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="C:\\USERS\\IANCH\\APPDATA\\LOCAL\\MICROSOFT\\MICROSOFT SQL SERVER LOCAL DB\\INSTANCES\\MS" +
		"SQLLOCALDB\\IAN1.MDF")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBANKACCOUNT(BANKACCOUNT instance);
    partial void UpdateBANKACCOUNT(BANKACCOUNT instance);
    partial void DeleteBANKACCOUNT(BANKACCOUNT instance);
    partial void InsertCUSTOMER(CUSTOMER instance);
    partial void UpdateCUSTOMER(CUSTOMER instance);
    partial void DeleteCUSTOMER(CUSTOMER instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::WPFPages.Properties.Settings.Default.C__USERS_IANCH_APPDATA_LOCAL_MICROSOFT_MICROSOFT_SQL_SERVER_LOCAL_DB_INSTANCES_MSSQLLOCALDB_IAN1_MDFConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BANKACCOUNT> BANKACCOUNTs
		{
			get
			{
				return this.GetTable<BANKACCOUNT>();
			}
		}
		
		public System.Data.Linq.Table<CUSTOMER> CUSTOMERs
		{
			get
			{
				return this.GetTable<CUSTOMER>();
			}
		}
		
		public System.Data.Linq.Table<SECACCOUNT> SECACCOUNTs
		{
			get
			{
				return this.GetTable<SECACCOUNT>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BANKACCOUNT")]
	public partial class BANKACCOUNT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _BANKNO;
		
		private string _CUSTNO;
		
		private int _ACTYPE;
		
		private decimal _BALANCE;
		
		private decimal _INTRATE;
		
		private System.DateTime _ODATE;
		
		private System.Nullable<System.DateTime> _CDATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBANKNOChanging(string value);
    partial void OnBANKNOChanged();
    partial void OnCUSTNOChanging(string value);
    partial void OnCUSTNOChanged();
    partial void OnACTYPEChanging(int value);
    partial void OnACTYPEChanged();
    partial void OnBALANCEChanging(decimal value);
    partial void OnBALANCEChanged();
    partial void OnINTRATEChanging(decimal value);
    partial void OnINTRATEChanged();
    partial void OnODATEChanging(System.DateTime value);
    partial void OnODATEChanged();
    partial void OnCDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCDATEChanged();
    #endregion
		
		public BANKACCOUNT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANKNO", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string BANKNO
		{
			get
			{
				return this._BANKNO;
			}
			set
			{
				if ((this._BANKNO != value))
				{
					this.OnBANKNOChanging(value);
					this.SendPropertyChanging();
					this._BANKNO = value;
					this.SendPropertyChanged("BANKNO");
					this.OnBANKNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTNO", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string CUSTNO
		{
			get
			{
				return this._CUSTNO;
			}
			set
			{
				if ((this._CUSTNO != value))
				{
					this.OnCUSTNOChanging(value);
					this.SendPropertyChanging();
					this._CUSTNO = value;
					this.SendPropertyChanged("CUSTNO");
					this.OnCUSTNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTYPE", DbType="Int NOT NULL")]
		public int ACTYPE
		{
			get
			{
				return this._ACTYPE;
			}
			set
			{
				if ((this._ACTYPE != value))
				{
					this.OnACTYPEChanging(value);
					this.SendPropertyChanging();
					this._ACTYPE = value;
					this.SendPropertyChanged("ACTYPE");
					this.OnACTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BALANCE", DbType="Decimal(12,2) NOT NULL")]
		public decimal BALANCE
		{
			get
			{
				return this._BALANCE;
			}
			set
			{
				if ((this._BALANCE != value))
				{
					this.OnBALANCEChanging(value);
					this.SendPropertyChanging();
					this._BALANCE = value;
					this.SendPropertyChanged("BALANCE");
					this.OnBALANCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTRATE", DbType="Decimal(12,2) NOT NULL")]
		public decimal INTRATE
		{
			get
			{
				return this._INTRATE;
			}
			set
			{
				if ((this._INTRATE != value))
				{
					this.OnINTRATEChanging(value);
					this.SendPropertyChanging();
					this._INTRATE = value;
					this.SendPropertyChanged("INTRATE");
					this.OnINTRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ODATE", DbType="Date NOT NULL")]
		public System.DateTime ODATE
		{
			get
			{
				return this._ODATE;
			}
			set
			{
				if ((this._ODATE != value))
				{
					this.OnODATEChanging(value);
					this.SendPropertyChanging();
					this._ODATE = value;
					this.SendPropertyChanged("ODATE");
					this.OnODATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CDATE", DbType="Date")]
		public System.Nullable<System.DateTime> CDATE
		{
			get
			{
				return this._CDATE;
			}
			set
			{
				if ((this._CDATE != value))
				{
					this.OnCDATEChanging(value);
					this.SendPropertyChanging();
					this._CDATE = value;
					this.SendPropertyChanged("CDATE");
					this.OnCDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CUSTOMER")]
	public partial class CUSTOMER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _CUSTNO;
		
		private string _BANKNO;
		
		private string _ACTYPE;
		
		private string _FNAME;
		
		private string _LNAME;
		
		private string _ADDR1;
		
		private string _ADDR2;
		
		private string _TOWN;
		
		private string _COUNTY;
		
		private string _PCODE;
		
		private string _PHONE;
		
		private string _MOBILE;
		
		private System.DateTime _DOB;
		
		private System.DateTime _ODATE;
		
		private System.Nullable<System.DateTime> _CDATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCUSTNOChanging(string value);
    partial void OnCUSTNOChanged();
    partial void OnBANKNOChanging(string value);
    partial void OnBANKNOChanged();
    partial void OnACTYPEChanging(string value);
    partial void OnACTYPEChanged();
    partial void OnFNAMEChanging(string value);
    partial void OnFNAMEChanged();
    partial void OnLNAMEChanging(string value);
    partial void OnLNAMEChanged();
    partial void OnADDR1Changing(string value);
    partial void OnADDR1Changed();
    partial void OnADDR2Changing(string value);
    partial void OnADDR2Changed();
    partial void OnTOWNChanging(string value);
    partial void OnTOWNChanged();
    partial void OnCOUNTYChanging(string value);
    partial void OnCOUNTYChanged();
    partial void OnPCODEChanging(string value);
    partial void OnPCODEChanged();
    partial void OnPHONEChanging(string value);
    partial void OnPHONEChanged();
    partial void OnMOBILEChanging(string value);
    partial void OnMOBILEChanged();
    partial void OnDOBChanging(System.DateTime value);
    partial void OnDOBChanged();
    partial void OnODATEChanging(System.DateTime value);
    partial void OnODATEChanged();
    partial void OnCDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCDATEChanged();
    #endregion
		
		public CUSTOMER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTNO", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string CUSTNO
		{
			get
			{
				return this._CUSTNO;
			}
			set
			{
				if ((this._CUSTNO != value))
				{
					this.OnCUSTNOChanging(value);
					this.SendPropertyChanging();
					this._CUSTNO = value;
					this.SendPropertyChanged("CUSTNO");
					this.OnCUSTNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANKNO", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string BANKNO
		{
			get
			{
				return this._BANKNO;
			}
			set
			{
				if ((this._BANKNO != value))
				{
					this.OnBANKNOChanging(value);
					this.SendPropertyChanging();
					this._BANKNO = value;
					this.SendPropertyChanged("BANKNO");
					this.OnBANKNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTYPE", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string ACTYPE
		{
			get
			{
				return this._ACTYPE;
			}
			set
			{
				if ((this._ACTYPE != value))
				{
					this.OnACTYPEChanging(value);
					this.SendPropertyChanging();
					this._ACTYPE = value;
					this.SendPropertyChanged("ACTYPE");
					this.OnACTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNAME", DbType="NVarChar(70) NOT NULL", CanBeNull=false)]
		public string FNAME
		{
			get
			{
				return this._FNAME;
			}
			set
			{
				if ((this._FNAME != value))
				{
					this.OnFNAMEChanging(value);
					this.SendPropertyChanging();
					this._FNAME = value;
					this.SendPropertyChanged("FNAME");
					this.OnFNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LNAME", DbType="NVarChar(70) NOT NULL", CanBeNull=false)]
		public string LNAME
		{
			get
			{
				return this._LNAME;
			}
			set
			{
				if ((this._LNAME != value))
				{
					this.OnLNAMEChanging(value);
					this.SendPropertyChanging();
					this._LNAME = value;
					this.SendPropertyChanged("LNAME");
					this.OnLNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDR1", DbType="NVarChar(70) NOT NULL", CanBeNull=false)]
		public string ADDR1
		{
			get
			{
				return this._ADDR1;
			}
			set
			{
				if ((this._ADDR1 != value))
				{
					this.OnADDR1Changing(value);
					this.SendPropertyChanging();
					this._ADDR1 = value;
					this.SendPropertyChanged("ADDR1");
					this.OnADDR1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDR2", DbType="NVarChar(70)")]
		public string ADDR2
		{
			get
			{
				return this._ADDR2;
			}
			set
			{
				if ((this._ADDR2 != value))
				{
					this.OnADDR2Changing(value);
					this.SendPropertyChanging();
					this._ADDR2 = value;
					this.SendPropertyChanged("ADDR2");
					this.OnADDR2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOWN", DbType="NVarChar(70) NOT NULL", CanBeNull=false)]
		public string TOWN
		{
			get
			{
				return this._TOWN;
			}
			set
			{
				if ((this._TOWN != value))
				{
					this.OnTOWNChanging(value);
					this.SendPropertyChanging();
					this._TOWN = value;
					this.SendPropertyChanged("TOWN");
					this.OnTOWNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTY", DbType="NVarChar(70) NOT NULL", CanBeNull=false)]
		public string COUNTY
		{
			get
			{
				return this._COUNTY;
			}
			set
			{
				if ((this._COUNTY != value))
				{
					this.OnCOUNTYChanging(value);
					this.SendPropertyChanging();
					this._COUNTY = value;
					this.SendPropertyChanged("COUNTY");
					this.OnCOUNTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCODE", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string PCODE
		{
			get
			{
				return this._PCODE;
			}
			set
			{
				if ((this._PCODE != value))
				{
					this.OnPCODEChanging(value);
					this.SendPropertyChanging();
					this._PCODE = value;
					this.SendPropertyChanged("PCODE");
					this.OnPCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string PHONE
		{
			get
			{
				return this._PHONE;
			}
			set
			{
				if ((this._PHONE != value))
				{
					this.OnPHONEChanging(value);
					this.SendPropertyChanging();
					this._PHONE = value;
					this.SendPropertyChanged("PHONE");
					this.OnPHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOBILE", DbType="NVarChar(20)")]
		public string MOBILE
		{
			get
			{
				return this._MOBILE;
			}
			set
			{
				if ((this._MOBILE != value))
				{
					this.OnMOBILEChanging(value);
					this.SendPropertyChanging();
					this._MOBILE = value;
					this.SendPropertyChanged("MOBILE");
					this.OnMOBILEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date NOT NULL")]
		public System.DateTime DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ODATE", DbType="Date NOT NULL")]
		public System.DateTime ODATE
		{
			get
			{
				return this._ODATE;
			}
			set
			{
				if ((this._ODATE != value))
				{
					this.OnODATEChanging(value);
					this.SendPropertyChanging();
					this._ODATE = value;
					this.SendPropertyChanged("ODATE");
					this.OnODATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CDATE", DbType="Date")]
		public System.Nullable<System.DateTime> CDATE
		{
			get
			{
				return this._CDATE;
			}
			set
			{
				if ((this._CDATE != value))
				{
					this.OnCDATEChanging(value);
					this.SendPropertyChanging();
					this._CDATE = value;
					this.SendPropertyChanged("CDATE");
					this.OnCDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SECACCOUNTS")]
	public partial class SECACCOUNT
	{
		
		private int _Id;
		
		private string _BANKNO;
		
		private string _CUSTNO;
		
		private int _ACTYPE;
		
		private decimal _BALANCE;
		
		private decimal _INTRATE;
		
		private System.DateTime _ODATE;
		
		private System.Nullable<System.DateTime> _CDATE;
		
		public SECACCOUNT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANKNO", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string BANKNO
		{
			get
			{
				return this._BANKNO;
			}
			set
			{
				if ((this._BANKNO != value))
				{
					this._BANKNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTNO", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string CUSTNO
		{
			get
			{
				return this._CUSTNO;
			}
			set
			{
				if ((this._CUSTNO != value))
				{
					this._CUSTNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTYPE", DbType="Int NOT NULL")]
		public int ACTYPE
		{
			get
			{
				return this._ACTYPE;
			}
			set
			{
				if ((this._ACTYPE != value))
				{
					this._ACTYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BALANCE", DbType="Decimal(12,2) NOT NULL")]
		public decimal BALANCE
		{
			get
			{
				return this._BALANCE;
			}
			set
			{
				if ((this._BALANCE != value))
				{
					this._BALANCE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTRATE", DbType="Decimal(12,2) NOT NULL")]
		public decimal INTRATE
		{
			get
			{
				return this._INTRATE;
			}
			set
			{
				if ((this._INTRATE != value))
				{
					this._INTRATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ODATE", DbType="Date NOT NULL")]
		public System.DateTime ODATE
		{
			get
			{
				return this._ODATE;
			}
			set
			{
				if ((this._ODATE != value))
				{
					this._ODATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CDATE", DbType="Date")]
		public System.Nullable<System.DateTime> CDATE
		{
			get
			{
				return this._CDATE;
			}
			set
			{
				if ((this._CDATE != value))
				{
					this._CDATE = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
